### ISSUE TITLE
can you edit the latest comic article?

### ISSUE THREAD

**Issue by xloem** [theusaf/explainXKCDBot#3]
hi theusaf,

I am trying to add this revision to the latest article: https://bafybeigzz7wasncuwtankdhkune7rt2gyfmav7zpi4th2rsen62fyn2tgy.ipfs.dweb.link/2022-07-21T16:37-04:00.txt

The article url is https://www.explainxkcd.com/wiki/index.php/2648:_Chemicals .

When I do this I am experiencing these things:
- the edit is ignored and does not enter the history
- sometimes the page is replaced by what appears to be aggressive vandalism, simultaneous to my edit

Judging by the discussion, many others are having these issues too, but not all the time nor everyone.

Are you in contact with the host if the server was compromised by a vandal?

**Comment by theusaf** [comment]
At the moment, there are a lot of vandals attacking the site, but the server isn't compromised (probably). The ignored edit was caused due to some changes I made to attempt to counter spam, this should be fixed now. Thanks for the report though!

**Comment by xloem** [comment]
Thank you, theusaf. Others left comments that editing wasn't working (`I think the site itself is hijacked, since the edits don't show properly.[162.158.48.127](https://www.explainxkcd.com/wiki/index.php/Special:Contributions/162.158.48.127) 06:07, 21 July 2022 (UTC)`). I couldn't even add a comment yesterday; I don't know how that poster did. If you have time, it could be kind to leave a follow-up comment on the page explaining the prevention of edits. Thank you for your hard work.
