### ISSUE TITLE
Not Functioning

### ISSUE THREAD

**Issue by Mapron01** [theusaf/explainXKCDBot#4]
The bot is failing to deal with a rather majpor troll attack on today's comic, involving the troll making edits that remove over 1000 characters

**Comment by theusaf** [comment]
The bot blocks things based on certain criteria to try to block spam and not block regular edits. However, there is always ways to circumvent such filters, creating a constant cat and mouse situation.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
